server:
    port: 8080

test1-datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.207/database1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: tmmysql123

test2-datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:  jdbc:mysql://192.168.1.207/database2?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: tmmysql123

